<h1 id="16_">16. 预定义异常</h1>
<h2 id="16_1">16.1 Exception</h2>
<p>(PHP 5, PHP 7)</p>
<h3 id="简介">简介</h3>
<p><strong>Exception</strong>是所有异常的基类.</p>
<h3 id="类摘要">类摘要</h3>
<p><strong>Exception</strong> {</p>
<p>/* 属性 */</p>
<p>protected string <a href="class.exception.html#exception.props.message">$message</a> ;</p>
<p>protected int <a href="class.exception.html#exception.props.code">$code</a> ;</p>
<p>protected string <a href="class.exception.html#exception.props.file">$file</a> ;</p>
<p>protected int <a href="class.exception.html#exception.props.line">$line</a> ;</p>
<p>/* 方法 */</p>
<p>public <a href="exception.construct.html">__construct</a> ([ string <code>$message</code> = "" [, int <code>$code</code> = 0 [, Throwable <code>$previous</code> = <strong><code>NULL</code></strong> ]]] )</p>
<p>final public <a href="exception.getmessage.html">getMessage</a> ( void ) : string</p>
<p>final public <a href="exception.getprevious.html">getPrevious</a> ( void ) : Throwable</p>
<p>final public <a href="exception.getcode.html">getCode</a> ( void ) : int</p>
<p>final public <a href="exception.getfile.html">getFile</a> ( void ) : string</p>
<p>final public <a href="exception.getline.html">getLine</a> ( void ) : int</p>
<p>final public <a href="exception.gettrace.html">getTrace</a> ( void ) : array</p>
<p>final public <a href="exception.gettraceasstring.html">getTraceAsString</a> ( void ) : string</p>
<p>public <a href="exception.tostring.html">__toString</a> ( void ) : string</p>
<p>final private <a href="exception.clone.html">__clone</a> ( void ) : void</p>
<p>}</p>
<h3 id="属性">属性</h3>
<p>message</p>
<p>异常消息内容</p>
<p>code</p>
<p>异常代码</p>
<p>file</p>
<p>抛出异常的文件名</p>
<p>line</p>
<p>抛出异常在该文件中的行号</p>
<h3 id="Table">Table of Contents</h3>
<ul>
<li><a href="exception.construct.html">Exception::__construct</a> - 异常构造函数</li>
<li><a href="exception.getmessage.html">Exception::getMessage</a> - 获取异常消息内容</li>
<li><a href="exception.getprevious.html">Exception::getPrevious</a> - 返回异常链中的前一个异常</li>
<li><a href="exception.getcode.html">Exception::getCode</a> - 获取异常代码</li>
<li><a href="exception.getfile.html">Exception::getFile</a> - 创建异常时的程序文件名称</li>
<li><a href="exception.getline.html">Exception::getLine</a> - 获取创建的异常所在文件中的行号</li>
<li><a href="exception.gettrace.html">Exception::getTrace</a> - 获取异常追踪信息</li>
<li><a href="exception.gettraceasstring.html">Exception::getTraceAsString</a> - 获取字符串类型的异常追踪信息</li>
<li><a href="exception.tostring.html">Exception::__toString</a> - 将异常对象转换为字符串</li>
<li><a href="exception.clone.html">Exception::__clone</a> - 异常克隆</li>
</ul>
<h2 id="16_2">16.2 ErrorException</h2>
<p>(PHP 5 &gt;= 5.1.0, PHP 7)</p>
<h3 id="简介">简介</h3>
<p>错误异常.</p>
<h3 id="类摘要">类摘要</h3>
<p><strong>ErrorException</strong> extends <a href="class.exception.html">Exception</a> {</p>
<p>/* 属性 */</p>
<p>protected int <a href="class.errorexception.html#errorexception.props.severity">$severity</a> ;</p>
<p>/* 方法 */</p>
<p>public <a href="errorexception.construct.html">__construct</a> ([ string <code>$message</code> = "" [, int <code>$code</code> = 0 [, int <code>$severity</code> = E_ERROR [, string <code>$filename</code> = __FILE__ [, int <code>$lineno</code> = __LINE__ [, <a href="class.exception.html">Exception</a> <code>$previous</code> = <strong><code>NULL</code></strong> ]]]]]] )</p>
<p>final public <a href="errorexception.getseverity.html">getSeverity</a> ( void ) : int</p>
<p>/* 继承的方法 */</p>
<p>final public <a href="exception.getmessage.html">Exception::getMessage</a> ( void ) : string</p>
<p>final public <a href="exception.getprevious.html">Exception::getPrevious</a> ( void ) : Throwable</p>
<p>final public <a href="exception.getcode.html">Exception::getCode</a> ( void ) : int</p>
<p>final public <a href="exception.getfile.html">Exception::getFile</a> ( void ) : string</p>
<p>final public <a href="exception.getline.html">Exception::getLine</a> ( void ) : int</p>
<p>final public <a href="exception.gettrace.html">Exception::getTrace</a> ( void ) : array</p>
<p>final public <a href="exception.gettraceasstring.html">Exception::getTraceAsString</a> ( void ) : string</p>
<p>public <a href="exception.tostring.html">Exception::__toString</a> ( void ) : string</p>
<p>final private <a href="exception.clone.html">Exception::__clone</a> ( void ) : void</p>
<p>}</p>
<h3 id="属性">属性</h3>
<p>severity</p>
<p>异常级别</p>
<h3 id="范例">范例</h3>
<p><strong>Example #1 使用<a href="function.set-error-handler.html">set_error_handler()</a>函数将错误信息托管至ErrorException</strong></p>
<pre class="prettyprint"><code class="php language-php">&lt;?php  
function exception_error_handler($errno, $errstr, $errfile, $errline ) {  
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);  
}  
set_error_handler("exception_error_handler");  

/* Trigger exception */  
strpos();  
?&gt;
</code></pre>
<p>以上例程的输出类似于:</p>
<p>Fatal error: Uncaught exception 'ErrorException' with message 'Wrong parameter count for strpos()' in /home/bjori/tmp/ex.php:8
Stack trace:</p>
<pre class="prettyprint"><code>#0 \[internal function\]: exception\_error\_handler(2, 'Wrong parameter...', '/home/bjori/php...', 8, Array)
#1 /home/bjori/php/cleandocs/test.php(8): strpos()
#2 {main}
  thrown in /home/bjori/tmp/ex.php on line 8
</code></pre>
<h3 id="Table">Table of Contents</h3>
<ul>
<li><a href="errorexception.construct.html">ErrorException::__construct</a> - 构造一个异常(Exception)</li>
<li><a href="errorexception.getseverity.html">ErrorException::getSeverity</a> - 获取异常的严重程度</li>
</ul>